server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/account
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600

springdoc:
  swagger-ui:
    path: /swagger-uis