eureka:
  instance:
    hostname: discovery-service.internal
  client:
    service-url:
      defaultZone: http://discovery-service.internal:8761/eureka/
spring:
  cloud:
    config:
      override-system-properties: true