eureka:
  instance:
    hostname: discovery-service.internal
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service.internal:8761/eureka/

server:
  port: 8761

spring:
  cloud:
    config:
      uri: http://config-server.internal:8000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always