eureka:
  instance:
    hostname: discovery-service
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

server:
  port: 8761

spring:
  cloud:
    config:
      uri: http://config-server:8000

management:
  endpoints:
    web:
      exposure:
        include: "info,health,env"
  endpoint:
    health:
      show-details: always
