server:
  port: 8004

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/transaction
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true