spring:
  config:
    import: optional:configserver:http://config-server:8000
  application:
    name: network-service

#
#server:
#  port: 8003
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/network
#    username: root
#    password: 123456
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#springdoc:
#  swagger-ui:
#    path: /swagger-ui