server:
  port: 8000
spring:
  profiles:
    active: native
  application:
    name: config-server.internal
  cloud:
    config:
      server:
        native:
          search-locations: file:/app/configurations/
management:
  endpoints:
    web:
      exposure:
        include: "*"