spring:
  config:
    import: optional:configserver:http://config-server.internal:8000
  application:
    name: account-service
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service.internal:8761/eureka/